" generated by unicodef: https://github.com/tsouanas/unicodef

inoremap \\eur €
inoremap \\gbp £
inoremap \\usd $
inoremap \\yen ¥
inoremap \\brl R$
inoremap \\crz ₢$
inoremap \\cent ¢
inoremap \\para ¶
inoremap \\sect §
inoremap \\Eth Ð
inoremap \\eth ð
inoremap \\Thorn Þ
inoremap \\thorn þ
inoremap \\degree °
inoremap \\copy ©
inoremap \\reg ®
inoremap \\estim ℮
